# Location Selection with E-NAUTILUS: Part 1 (with RPM)
_Generation of reference points_

In [1]:
from desdeo.problem import Constant, Problem, Objective, VariableTypeEnum, Constraint, TensorConstant, TensorVariable, ConstraintTypeEnum
import numpy as np
import pandas as pd
from slugify import slugify
# These are to just suppress warnings in the outputs of the example
import warnings
import pickle

warnings.filterwarnings("ignore")

## Model inputs

In [2]:

# Mininum expected attendance to be worth visiting 
min_att = 4

# Cost constants
# The current gas costs ($/gallon)
raw_dollars_per_gallon = 3.00

# The efficiency of the vehicle (miles/gallon)
raw_mpg = 6.0
# How long the event is (hours)
hours_per_event = 4
driver_salary_per_hour = 19
raw_driver_cost_per_trip = hours_per_event * driver_salary_per_hour

# Food desert threshold (minutes)
raw_food_desert_threshold = 15

## Helper functions

In [3]:
def no_nan(val):
    if pd.isna(val):
        return ""
    else:
        return str(val)

## Load and process Constants

In [4]:


home = "Ada"
# Read the adjacency matrix (distance in miles)
adjDist = pd.read_csv("data/adjacencyMatrixDist.csv", index_col=0)
dist2home = adjDist.loc[:,[home]].rename(columns={home:"dist2home"})
dist2home.index.name = "city"
display("Distance to home base")
display(dist2home)

# Read the adjacency matrix (travel time in minutes)
adjTTime = pd.read_csv("data/adjacencyMatrixTravelTime.csv", index_col=0)
display("Travel time adjacency matrix")
display(adjTTime)

# Read the cities 
cities = pd.read_csv("data/cities.csv")

# Data integrity check
cities_cities_df = set(cities.loc[:,"city"])
cities_adjDist_df = set(adjDist.index)
if cities_cities_df != cities_adjDist_df: 
    raise ValueError(f"The city table and the adjacency matrix have differing cities.\nCity table: {cities_cities_df}\nAdjacency matrix{cities_adjDist_df}")

'Distance to home base'

                dist2home
city
Ada                  0.00
Alger                8.81
Bluffton            19.50
Cairo               31.26
Caledonia          102.21
Carey               66.05
Columbus Grove      36.16
Continental         70.66
Cridersville        38.76
Delphos             51.03
Dunkirk             17.85
Elida               44.79
Forest              35.97
Fort Jennings       57.86
Glandorf            50.50
Kalida              52.05
Kenton              24.99
La Rue              52.09
Leipsic             48.76
Lima                26.28
Marion              91.69
Minster             84.84
Mount Victory       39.74
Nevada              71.70
New Bremen          79.50
New Knoxville       69.38
Ottawa              47.60
Ottoville           60.42
Pandora             35.75
Prospect            78.84
Saint Marys         69.13
Spencerville        49.06
Sycamore            68.87
Upper Sandusky      53.51
Wapakoneta          50.39
Waynesfield         34.99

'Travel time adjacency matrix'

,Ada,Alger,Bluffton,Cairo,Caledonia,Carey,Columbus Grove,Continental,Cridersville,Delphos,...,Ottawa,Ottoville,Pandora,Prospect,Saint Marys,Spencerville,Sycamore,Upper Sandusky,Wapakoneta,Waynesfield
Ada,0.00,9.30,20.48,23.63,70.40,45.55,31.78,62.73,35.73,35.74,...,41.59,42.32,31.00,72.88,51.50,50.39,51.19,38.63,39.70,32.14
Alger,9.30,0.00,29.61,32.76,79.53,54.68,40.91,71.86,36.43,44.88,...,50.72,51.45,37.84,73.76,52.20,51.39,60.32,47.76,40.39,22.95
Bluffton,20.48,29.61,0.00,18.42,76.23,36.78,20.55,49.98,29.81,30.53,...,26.52,37.11,15.30,84.11,45.58,45.18,56.07,44.46,33.78,37.66
Cairo,23.63,32.76,18.42,0.00,78.76,51.34,11.29,42.34,26.10,17.40,...,19.81,23.98,20.73,86.64,43.96,32.74,59.54,46.98,32.15,37.08
Caledonia,70.40,79.53,76.23,78.76,0.00,47.25,87.77,118.71,95.99,91.73,...,96.46,98.31,86.98,28.59,111.76,107.07,49.45,34.24,99.96,90.16
Carey,45.55,54.68,36.78,51.34,47.25,0.00,57.96,78.84,63.76,64.48,...,55.38,71.06,48.79,53.68,79.53,79.13,19.29,15.77,67.73,71.61
Columbus Grove,31.78,40.91,20.55,11.29,87.77,57.96,0.00,32.45,35.78,27.08,...,9.92,28.86,9.43,94.52,53.64,42.42,67.42,54.87,41.84,46.76
Continental,62.73,71.86,49.98,42.34,118.71,78.84,32.45,0.00,63.28,36.13,...,23.51,26.32,41.28,126.22,74.44,52.23,97.36,86.57,69.34,74.72
Cridersville,35.73,36.43,29.81,26.10,95.99,63.76,35.78,63.28,0.00,36.77,...,44.46,43.35,35.31,101.02,28.29,30.89,74.39,61.84,16.48,27.29
Delphos,35.74,44.88,30.53,17.40,91.73,64.48,27.08,36.13,36.77,0.00,...,35.47,10.96,36.38,99.67,39.11,16.90,72.58,60.02,39.91,48.70
Dunkirk,18.74,27.87,26.69,29.21,59.40,33.70,37.09,68.80,44.07,42.25,...,47.69,48.42,37.10,64.92,61.88,57.18,40.22,27.67,50.07,50.14
Elida,35.72,39.09,30.50,17.23,91.70,64.45,26.91,47.81,24.93,14.07,...,35.59,21.85,36.18,100.05,42.63,22.80,72.96,60.40,30.52,36.73
Forest,27.32,36.46,33.15,35.68,51.67,25.98,43.56,75.27,50.53,48.72,...,53.77,54.51,43.18,55.06,67.96,63.27,32.69,20.14,56.16,53.77
Fort Jennings,43.19,52.32,37.97,24.84,99.17,71.92,24.18,26.77,44.21,10.26,...,28.09,5.28,33.62,107.12,48.57,26.36,80.02,67.47,49.38,56.14
Glandorf,45.77,54.89,31.63,23.99,101.58,60.49,14.10,24.74,48.64,36.88,...,5.16,27.83,22.93,108.50,66.33,52.98,79.01,68.85,54.53,59.46
Kalida,43.13,52.26,37.91,24.30,99.11,70.10,22.78,19.60,43.68,22.69,...,14.77,13.63,32.21,106.62,61.00,38.79,79.52,66.97,49.73,55.12
Kenton,24.45,25.33,42.95,45.47,56.63,45.61,53.35,85.06,54.52,58.51,...,63.95,64.68,53.36,48.70,64.04,69.76,52.32,39.59,52.98,33.80
La Rue,50.69,51.56,66.02,68.55,40.17,50.21,76.42,108.13,80.76,81.58,...,86.64,87.38,76.05,25.93,90.28,96.00,52.56,34.57,79.21,60.03
Leipsic,48.20,57.33,29.78,32.32,96.62,55.53,22.43,25.95,56.94,47.98,...,13.49,40.91,21.90,103.90,73.64,63.45,74.05,65.99,61.84,65.72
Lima,26.32,28.07,21.10,12.31,87.28,55.05,22.00,49.95,14.94,23.93,...,30.99,30.34,26.80,92.98,32.44,24.60,65.89,53.33,20.63,25.35
Marion,63.48,65.53,69.31,71.84,15.84,38.88,79.71,111.42,86.69,84.87,...,89.53,91.37,80.04,16.59,104.82,100.13,42.51,27.31,93.02,75.64
Minster,67.17,67.87,61.26,59.63,127.44,95.21,69.31,92.29,43.96,56.95,...,77.11,67.86,66.60,103.18,18.00,40.06,105.68,93.12,32.90,48.83
Mount Victory,39.20,40.07,57.87,60.39,59.07,60.28,68.27,99.98,69.27,73.43,...,78.87,79.61,68.28,34.67,73.98,84.51,67.00,54.27,62.92,46.77
Nevada,48.33,57.46,54.16,56.68,36.09,23.73,64.56,96.27,71.53,69.72,...,74.23,76.08,64.75,43.25,89.53,84.84,18.97,13.53,77.72,79.89
New Bremen,61.95,62.65,56.04,54.41,122.22,89.99,64.09,87.17,38.74,51.83,...,72.05,62.74,61.54,97.95,12.88,34.94,100.62,88.07,27.77,43.77
New Knoxville,56.91,57.61,51.00,49.37,117.17,84.95,59.05,84.40,33.70,49.07,...,66.84,59.98,56.33,99.92,11.83,32.17,95.41,82.86,19.68,38.06
Ottawa,41.59,50.72,26.52,19.81,96.46,55.38,9.92,23.51,44.46,35.47,...,0.00,28.40,17.82,103.75,62.16,50.94,73.90,64.67,50.35,55.28
Ottoville,42.32,51.45,37.11,23.98,98.31,71.06,28.86,26.32,43.35,10.96,...,28.40,0.00,38.29,105.71,50.02,27.80,78.62,66.06,49.36,54.74
Pandora,31.00,37.84,15.30,20.73,86.98,48.79,9.43,41.28,35.31,36.38,...,17.82,38.29,0.00,92.56,52.01,51.61,65.46,52.90,40.21,44.09
Prospect,72.88,73.76,84.11,86.64,28.59,53.68,94.52,126.22,101.02,99.67,...,103.75,105.71,92.56,0.00,102.56,114.42,56.80,41.60,91.50,80.23
Saint Marys,51.50,52.20,45.58,43.96,111.76,79.53,53.64,74.44,28.29,39.11,...,62.16,50.02,52.01,102.56,0.00,22.21,90.79,78.23,15.05,33.43
Spencerville,50.39,51.39,45.18,32.74,107.07,79.13,42.42,52.23,30.89,16.90,...,50.94,27.80,51.61,114.42,22.21,0.00,87.72,75.16,25.43,45.41
Sycamore,51.19,60.32,56.07,59.54,49.45,19.29,67.42,97.36,74.39,72.58,...,73.90,78.62,65.46,56.80,90.79,87.72,0.00,18.05,80.92,83.08
Upper Sandusky,38.63,47.76,44.46,46.98,34.24,15.77,54.87,86.57,61.84,60.02,...,64.67,66.06,52.90,41.60,78.23,75.16,18.05,0.00,67.50,69.67
Wapakoneta,39.70,40.39,33.78,32.15,99.96,67.73,41.84,69.34,16.48,39.91,...,50.35,49.36,40.21,91.50,15.05,25.43,80.92,67.50,0.00,21.86
Waynesfield,32.14,22.95,37.66,37.08,90.16,71.61,46.76,74.72,27.29,48.70,...,55.28,54.74,44.09,80.23,33.43,45.41,83.08,69.67,21.86,0.00

### Site table

In [5]:
sites_only = pd.read_csv("data/proposedSitesProcessed.csv", index_col=0)

# Data integrity check
cities_cities_df = set(cities.loc[:,"city"])
cities_adjDist_df = set(sites_only.loc[:,"city"])
if len(cities_adjDist_df - cities_cities_df) != 0: 
    print(cities_adjDist_df - cities_cities_df)
    raise ValueError(f"Some cities in the site table don't appear in the city table.\nCity table: {cities_cities_df}\nSite table{cities_adjDist_df}")

# Create event table
sites = pd.merge(sites_only,cities,  on="city")
display(sites)
sites.loc[:, "site_id"] = sites.apply(lambda row: slugify(f'{row["city"]} {row["siteName"]}'), axis=1)
sites.loc[:, "site_pretty"] = sites.apply(lambda row: f'{row["siteName"]}', axis=1)

# Add the distance to home for each site 
sites = pd.merge(sites, dist2home, on="city")

display(sites)

,siteName,siteType,city,minAtt,medAtt,maxAtt,lat,long,pop,svi
0,Alger Dinner,charitable meal,Alger,1.0,3.0,5.0,40.709722,-83.844167,837,0.594200
1,DJ Kirk,charitable meal,Dunkirk,3.0,3.0,3.0,40.788056,-83.642778,774,0.547500
2,DJ Kirk,charitable meal,Dunkirk,2.0,2.0,2.0,40.788056,-83.642778,774,0.547500
3,Dunkirk Dinner,charitable meal,Dunkirk,3.0,3.0,7.0,40.788056,-83.642778,774,0.547500
4,Lima ODB,charitable meal,Lima,2.0,3.0,4.0,40.746389,-84.123333,35579,0.923333
5,Saint Marks UMC,church,Lima,2.0,3.0,7.0,40.746389,-84.123333,35579,0.923333
6,Wapak UCC,church,Wapakoneta,6.0,6.0,6.0,40.565556,-84.191111,9957,0.472500
7,Grace Clinics,clinic,Marion,0.0,3.0,10.0,40.620000,-83.126389,35999,0.932500
8,Christian Corner,food bank,Lima,0.0,6.0,10.0,40.746389,-84.123333,35579,0.923333
9,Alger Food Pantry,food pantry,Alger,2.0,4.0,6.0,40.709722,-83.844167,837,0.594200
10,Agape,food pantry;thrift store,Saint Marys,0.0,0.0,6.0,40.548889,-84.373333,8397,0.437500
11,Apape,food pantry;thrift store,Saint Marys,2.0,2.0,2.0,40.548889,-84.373333,8397,0.437500
12,HardinCrest,food pantry;thrift store,Kenton,2.0,3.0,5.0,40.646667,-83.622500,7947,0.918300
13,Kenton YMCA,gym,Kenton,3.0,3.0,3.0,40.646667,-83.622500,7947,0.918300
14,YMCA,gym,Kenton,0.0,2.0,4.0,40.646667,-83.622500,7947,0.918300
15,Bluffton Library,library,Bluffton,4.0,7.0,10.0,40.889444,-83.879167,3967,0.450800
16,Lima Library,library,Lima,3.0,3.0,3.0,40.746389,-84.123333,35579,0.923333
17,Public Library,library,Ada,3.0,6.0,10.0,40.768056,-83.825278,5334,0.390000
18,Public Library,library,Alger,3.0,6.0,10.0,40.709722,-83.844167,837,0.594200
19,Public Library,library,Cairo,3.0,6.0,10.0,40.830833,-84.084444,517,0.190000
20,Public Library,library,Caledonia,3.0,6.0,10.0,40.636389,-82.969444,560,0.327500
21,Public Library,library,Carey,3.0,6.0,10.0,40.949444,-83.376111,3565,0.414200
22,Public Library,library,Columbus Grove,3.0,6.0,10.0,40.920556,-84.059722,2160,0.350800
23,Public Library,library,Continental,3.0,6.0,10.0,41.100278,-84.272500,1102,0.399200
24,Public Library,library,Delphos,3.0,6.0,10.0,40.861111,-84.350000,7117,0.562500
25,Public Library,library,Elida,3.0,6.0,10.0,40.786667,-84.198889,1923,0.565000
26,Public Library,library,Forest,3.0,6.0,10.0,40.805000,-83.511667,1350,0.195800
27,Public Library,library,Fort Jennings,3.0,6.0,10.0,40.906944,-84.299722,525,0.100000
28,Public Library,library,Kalida,3.0,6.0,10.0,40.985278,-84.194444,1455,0.067500
29,Public Library,library,Leipsic,3.0,6.0,10.0,41.113889,-83.962500,2177,0.711700
30,Public Library,library,Mount Victory,3.0,6.0,10.0,40.533611,-83.521111,601,0.660000
31,Public Library,library,Ottawa,3.0,6.0,10.0,41.008333,-84.037500,4456,0.321700
32,Public Library,library,Ottoville,3.0,6.0,10.0,40.934167,-84.338333,966,0.062500
33,Public Library,library,Pandora,3.0,6.0,10.0,40.947500,-83.956667,1204,0.105800
34,Public Library,library,Saint Marys,3.0,6.0,10.0,40.548889,-84.373333,8397,0.437500
35,Public Library,library,Cridersville,3.0,6.0,10.0,40.664722,-84.130833,1791,0.676700
36,Public Library,library,Dunkirk,3.0,6.0,10.0,40.788056,-83.642778,774,0.547500
37,Public Library,library,Glandorf,3.0,6.0,10.0,41.027778,-84.079167,969,0.166250
38,Public Library,library,Kenton,3.0,6.0,10.0,40.646667,-83.622500,7947,0.918300
39,Public Library,library,La Rue,3.0,6.0,10.0,40.576389,-83.384722,676,0.163300
40,Public Library,library,Leipsic,3.0,6.0,10.0,41.113889,-83.962500,2177,0.711700
41,Public Library,library,Lima,3.0,6.0,10.0,40.746389,-84.123333,35579,0.923333
42,Public Library,library,Marion,3.0,6.0,10.0,40.620000,-83.126389,35999,0.932500
43,Public Library,library,Minster,3.0,6.0,10.0,40.393889,-84.376111,3046,0.263300
44,Public Library,library,Nevada,3.0,6.0,10.0,40.818611,-83.128333,706,0.348300
45,Public Library,library,New Bremen,3.0,6.0,10.0,40.436389,-84.379444,3034,0.095000
46,Public Library,library,New Knoxville,3.0,6.0,10.0,40.498333,-84.311111,946,0.246700
47,Public Library,library,Prospect,3.0,6.0,10.0,40.453889,-83.184722,1067,0.096700
48,Public Library,library,Spencerville,3.0,6.0,10.0,40.708056,-84.352778,2198,0.551700
49,Public Library,library,Sycamore,3.0,6.0,10.0,40.951667,-83.170833,793,0.195000
50,Public Library,library,Upper Sandusky,3.0,6.0,10.0,40.831111,-83.262500,6698,0.639200
51,Public Library,library,Wapakoneta,3.0,6.0,10.0,40.565556,-84.191111,9957,0.472500
52,Public Library,library,Waynesfield,3.0,6.0,10.0,40.602500,-83.973889,749,0.346700
53,Delphos Senior Center,senior community,Delphos,7.0,7.0,7.0,40.861111,-84.350000,7117,0.562500
54,HardinCrest,senior community,Kenton,2.0,3.0,5.0,40.646667,-83.622500,7947,0.918300
55,HardinCrest,senior community,Kenton,2.0,2.0,3.0,40.646667,-83.622500,7947,0.918300
56,Kenton Seton,senior community,Kenton,0.0,4.0,5.0,40.646667,-83.622500,7947,0.918300
57,Seton Kenton,senior community,Kenton,3.0,6.0,10.0,40.646667,-83.622500,7947,0.918300
58,Mercy Thrift Store,thrift store,Lima,0.0,1.0,4.0,40.746389,-84.123333,35579,0.923333
59,Restore,thrift store,Lima,3.0,3.0,9.0,40.746389,-84.123333,35579,0.923333

,siteName,siteType,city,minAtt,medAtt,maxAtt,lat,long,pop,svi,site_id,site_pretty,dist2home
0,Alger Dinner,charitable meal,Alger,1.0,3.0,5.0,40.709722,-83.844167,837,0.594200,alger-alger-dinner,Alger Dinner,8.81
1,DJ Kirk,charitable meal,Dunkirk,3.0,3.0,3.0,40.788056,-83.642778,774,0.547500,dunkirk-dj-kirk,DJ Kirk,17.85
2,DJ Kirk,charitable meal,Dunkirk,2.0,2.0,2.0,40.788056,-83.642778,774,0.547500,dunkirk-dj-kirk,DJ Kirk,17.85
3,Dunkirk Dinner,charitable meal,Dunkirk,3.0,3.0,7.0,40.788056,-83.642778,774,0.547500,dunkirk-dunkirk-dinner,Dunkirk Dinner,17.85
4,Lima ODB,charitable meal,Lima,2.0,3.0,4.0,40.746389,-84.123333,35579,0.923333,lima-lima-odb,Lima ODB,26.28
5,Saint Marks UMC,church,Lima,2.0,3.0,7.0,40.746389,-84.123333,35579,0.923333,lima-saint-marks-umc,Saint Marks UMC,26.28
6,Wapak UCC,church,Wapakoneta,6.0,6.0,6.0,40.565556,-84.191111,9957,0.472500,wapakoneta-wapak-ucc,Wapak UCC,50.39
7,Grace Clinics,clinic,Marion,0.0,3.0,10.0,40.620000,-83.126389,35999,0.932500,marion-grace-clinics,Grace Clinics,91.69
8,Christian Corner,food bank,Lima,0.0,6.0,10.0,40.746389,-84.123333,35579,0.923333,lima-christian-corner,Christian Corner,26.28
9,Alger Food Pantry,food pantry,Alger,2.0,4.0,6.0,40.709722,-83.844167,837,0.594200,alger-alger-food-pantry,Alger Food Pantry,8.81
10,Agape,food pantry;thrift store,Saint Marys,0.0,0.0,6.0,40.548889,-84.373333,8397,0.437500,saint-marys-agape,Agape,69.13
11,Apape,food pantry;thrift store,Saint Marys,2.0,2.0,2.0,40.548889,-84.373333,8397,0.437500,saint-marys-apape,Apape,69.13
12,HardinCrest,food pantry;thrift store,Kenton,2.0,3.0,5.0,40.646667,-83.622500,7947,0.918300,kenton-hardincrest,HardinCrest,24.99
13,Kenton YMCA,gym,Kenton,3.0,3.0,3.0,40.646667,-83.622500,7947,0.918300,kenton-kenton-ymca,Kenton YMCA,24.99
14,YMCA,gym,Kenton,0.0,2.0,4.0,40.646667,-83.622500,7947,0.918300,kenton-ymca,YMCA,24.99
15,Bluffton Library,library,Bluffton,4.0,7.0,10.0,40.889444,-83.879167,3967,0.450800,bluffton-bluffton-library,Bluffton Library,19.50
16,Lima Library,library,Lima,3.0,3.0,3.0,40.746389,-84.123333,35579,0.923333,lima-lima-library,Lima Library,26.28
17,Public Library,library,Ada,3.0,6.0,10.0,40.768056,-83.825278,5334,0.390000,ada-public-library,Public Library,0.00
18,Public Library,library,Alger,3.0,6.0,10.0,40.709722,-83.844167,837,0.594200,alger-public-library,Public Library,8.81
19,Public Library,library,Cairo,3.0,6.0,10.0,40.830833,-84.084444,517,0.190000,cairo-public-library,Public Library,31.26
20,Public Library,library,Caledonia,3.0,6.0,10.0,40.636389,-82.969444,560,0.327500,caledonia-public-library,Public Library,102.21
21,Public Library,library,Carey,3.0,6.0,10.0,40.949444,-83.376111,3565,0.414200,carey-public-library,Public Library,66.05
22,Public Library,library,Columbus Grove,3.0,6.0,10.0,40.920556,-84.059722,2160,0.350800,columbus-grove-public-library,Public Library,36.16
23,Public Library,library,Continental,3.0,6.0,10.0,41.100278,-84.272500,1102,0.399200,continental-public-library,Public Library,70.66
24,Public Library,library,Delphos,3.0,6.0,10.0,40.861111,-84.350000,7117,0.562500,delphos-public-library,Public Library,51.03
25,Public Library,library,Elida,3.0,6.0,10.0,40.786667,-84.198889,1923,0.565000,elida-public-library,Public Library,44.79
26,Public Library,library,Forest,3.0,6.0,10.0,40.805000,-83.511667,1350,0.195800,forest-public-library,Public Library,35.97
27,Public Library,library,Fort Jennings,3.0,6.0,10.0,40.906944,-84.299722,525,0.100000,fort-jennings-public-library,Public Library,57.86
28,Public Library,library,Kalida,3.0,6.0,10.0,40.985278,-84.194444,1455,0.067500,kalida-public-library,Public Library,52.05
29,Public Library,library,Leipsic,3.0,6.0,10.0,41.113889,-83.962500,2177,0.711700,leipsic-public-library,Public Library,48.76
30,Public Library,library,Mount Victory,3.0,6.0,10.0,40.533611,-83.521111,601,0.660000,mount-victory-public-library,Public Library,39.74
31,Public Library,library,Ottawa,3.0,6.0,10.0,41.008333,-84.037500,4456,0.321700,ottawa-public-library,Public Library,47.60
32,Public Library,library,Ottoville,3.0,6.0,10.0,40.934167,-84.338333,966,0.062500,ottoville-public-library,Public Library,60.42
33,Public Library,library,Pandora,3.0,6.0,10.0,40.947500,-83.956667,1204,0.105800,pandora-public-library,Public Library,35.75
34,Public Library,library,Saint Marys,3.0,6.0,10.0,40.548889,-84.373333,8397,0.437500,saint-marys-public-library,Public Library,69.13
35,Public Library,library,Cridersville,3.0,6.0,10.0,40.664722,-84.130833,1791,0.676700,cridersville-public-library,Public Library,38.76
36,Public Library,library,Dunkirk,3.0,6.0,10.0,40.788056,-83.642778,774,0.547500,dunkirk-public-library,Public Library,17.85
37,Public Library,library,Glandorf,3.0,6.0,10.0,41.027778,-84.079167,969,0.166250,glandorf-public-library,Public Library,50.50
38,Public Library,library,Kenton,3.0,6.0,10.0,40.646667,-83.622500,7947,0.918300,kenton-public-library,Public Library,24.99
39,Public Library,library,La Rue,3.0,6.0,10.0,40.576389,-83.384722,676,0.163300,la-rue-public-library,Public Library,52.09
40,Public Library,library,Leipsic,3.0,6.0,10.0,41.113889,-83.962500,2177,0.711700,leipsic-public-library,Public Library,48.76
41,Public Library,library,Lima,3.0,6.0,10.0,40.746389,-84.123333,35579,0.923333,lima-public-library,Public Library,26.28
42,Public Library,library,Marion,3.0,6.0,10.0,40.620000,-83.126389,35999,0.932500,marion-public-library,Public Library,91.69
43,Public Library,library,Minster,3.0,6.0,10.0,40.393889,-84.376111,3046,0.263300,minster-public-library,Public Library,84.84
44,Public Library,library,Nevada,3.0,6.0,10.0,40.818611,-83.128333,706,0.348300,nevada-public-library,Public Library,71.70
45,Public Library,library,New Bremen,3.0,6.0,10.0,40.436389,-84.379444,3034,0.095000,new-bremen-public-library,Public Library,79.50
46,Public Library,library,New Knoxville,3.0,6.0,10.0,40.498333,-84.311111,946,0.246700,new-knoxville-public-library,Public Library,69.38
47,Public Library,library,Prospect,3.0,6.0,10.0,40.453889,-83.184722,1067,0.096700,prospect-public-library,Public Library,78.84
48,Public Library,library,Spencerville,3.0,6.0,10.0,40.708056,-84.352778,2198,0.551700,spencerville-public-library,Public Library,49.06
49,Public Library,library,Sycamore,3.0,6.0,10.0,40.951667,-83.170833,793,0.195000,sycamore-public-library,Public Library,68.87
50,Public Library,library,Upper Sandusky,3.0,6.0,10.0,40.831111,-83.262500,6698,0.639200,upper-sandusky-public-library,Public Library,53.51
51,Public Library,library,Wapakoneta,3.0,6.0,10.0,40.565556,-84.191111,9957,0.472500,wapakoneta-public-library,Public Library,50.39
52,Public Library,library,Waynesfield,3.0,6.0,10.0,40.602500,-83.973889,749,0.346700,waynesfield-public-library,Public Library,34.99
53,Delphos Senior Center,senior community,Delphos,7.0,7.0,7.0,40.861111,-84.350000,7117,0.562500,delphos-delphos-senior-center,Delphos Senior Center,51.03
54,HardinCrest,senior community,Kenton,2.0,3.0,5.0,40.646667,-83.622500,7947,0.918300,kenton-hardincrest,HardinCrest,24.99
55,HardinCrest,senior community,Kenton,2.0,2.0,3.0,40.646667,-83.622500,7947,0.918300,kenton-hardincrest,HardinCrest,24.99
56,Kenton Seton,senior community,Kenton,0.0,4.0,5.0,40.646667,-83.622500,7947,0.918300,kenton-kenton-seton,Kenton Seton,24.99
57,Seton Kenton,senior community,Kenton,3.0,6.0,10.0,40.646667,-83.622500,7947,0.918300,kenton-seton-kenton,Seton Kenton,24.99
58,Mercy Thrift Store,thrift store,Lima,0.0,1.0,4.0,40.746389,-84.123333,35579,0.923333,lima-mercy-thrift-store,Mercy Thrift Store,26.28
59,Restore,thrift store,Lima,3.0,3.0,9.0,40.746389,-84.123333,35579,0.923333,lima-restore,Restore,26.28

### Close cities for events

In [6]:

close_cities = adjTTime < raw_food_desert_threshold
cities_adj2sites = sites.loc[:,["city", "site_id"]].merge(close_cities, left_on="city", right_index=True)
display(cities_adj2sites)
cities_adj2sites = (cities_adj2sites.iloc[:,2:].values).astype(int)
s_adj_raw = cities_adj2sites.T
display(cities_adj2sites.T.shape)
e_adj_raw_list = s_adj_raw.tolist()

,city,site_id,Ada,Alger,Bluffton,Cairo,Caledonia,Carey,Columbus Grove,Continental,...,Ottawa,Ottoville,Pandora,Prospect,Saint Marys,Spencerville,Sycamore,Upper Sandusky,Wapakoneta,Waynesfield
0,Alger,alger-alger-dinner,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,Dunkirk,dunkirk-dj-kirk,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Dunkirk,dunkirk-dj-kirk,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Dunkirk,dunkirk-dunkirk-dinner,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Lima,lima-lima-odb,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,Lima,lima-saint-marks-umc,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,Wapakoneta,wapakoneta-wapak-ucc,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
7,Marion,marion-grace-clinics,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,Lima,lima-christian-corner,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,Alger,alger-alger-food-pantry,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,Saint Marys,saint-marys-agape,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
11,Saint Marys,saint-marys-apape,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
12,Kenton,kenton-hardincrest,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,Kenton,kenton-kenton-ymca,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,Kenton,kenton-ymca,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,Bluffton,bluffton-bluffton-library,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,Lima,lima-lima-library,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,Ada,ada-public-library,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,Alger,alger-public-library,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,Cairo,cairo-public-library,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
20,Caledonia,caledonia-public-library,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,Carey,carey-public-library,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
22,Columbus Grove,columbus-grove-public-library,False,False,False,True,False,False,True,False,...,True,False,True,False,False,False,False,False,False,False
23,Continental,continental-public-library,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
24,Delphos,delphos-public-library,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
25,Elida,elida-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,Forest,forest-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,Fort Jennings,fort-jennings-public-library,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
28,Kalida,kalida-public-library,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
29,Leipsic,leipsic-public-library,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
30,Mount Victory,mount-victory-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,Ottawa,ottawa-public-library,False,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,False,False,False
32,Ottoville,ottoville-public-library,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
33,Pandora,pandora-public-library,False,False,False,False,False,False,True,False,...,False,False,True,False,False,False,False,False,False,False
34,Saint Marys,saint-marys-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
35,Cridersville,cridersville-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36,Dunkirk,dunkirk-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
37,Glandorf,glandorf-public-library,False,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,False,False,False
38,Kenton,kenton-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,La Rue,la-rue-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,Leipsic,leipsic-public-library,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
41,Lima,lima-public-library,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42,Marion,marion-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43,Minster,minster-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
44,Nevada,nevada-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
45,New Bremen,new-bremen-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
46,New Knoxville,new-knoxville-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
47,Prospect,prospect-public-library,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
48,Spencerville,spencerville-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
49,Sycamore,sycamore-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
50,Upper Sandusky,upper-sandusky-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
51,Wapakoneta,wapakoneta-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
52,Waynesfield,waynesfield-public-library,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
53,Delphos,delphos-delphos-senior-center,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
54,Kenton,kenton-hardincrest,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
55,Kenton,kenton-hardincrest,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56,Kenton,kenton-kenton-seton,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
57,Kenton,kenton-seton-kenton,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
58,Lima,lima-mercy-thrift-store,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59,Lima,lima-restore,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

(36, 60)

In [7]:
site_dist2home = sites.loc[:,["dist2home"]].T.values
site_dist2home_list = site_dist2home.tolist()

## Constants

In [8]:
site_count = sites.shape[0]

# Expected attenance 
raw_attendance = sites.loc[:,["medAtt"]] 
raw_under_attendance = (raw_attendance < min_att).astype(int)

# Site SVI
raw_svi = sites.loc[:,["svi"]]

svi = TensorConstant(name="Site SVI",
                     symbol="svi", 
                     shape=raw_svi.T.shape,
                     values=raw_svi.T.values.tolist())
display(svi)

# How many people to expect to attend each site
ea = TensorConstant(name="Expected attendance",
                                 symbol="ea", 
                                 shape=raw_attendance.T.shape,
                                 values=raw_attendance.T.values.tolist())
display(ea)

# How many sites are expected to be under attended? 
eua = TensorConstant(name="Expected under-attendance",
                    symbol="eua",
                    shape=raw_under_attendance.T.shape,
                    values=raw_under_attendance.T.values.tolist())

display(eua)

# Distance to home 
sd2h = TensorConstant(name="The distance to drive from home to a site",
                    symbol="sd2h",                        
                    shape=site_dist2home.shape,
                    values=site_dist2home_list)
display(sd2h)

mpg = Constant(name="Miles per gallon (miles/gallon)", 
               symbol="mpg", 
               value=raw_mpg)

display(mpg)
dpg = Constant(name="Dollars per gallon ($/gallon)", 
               symbol="dpg", 
               value=raw_dollars_per_gallon)

display(dpg)
dcpt = Constant(name="Driver cost per trip ($)", 
                                symbol="dcpt", 
                                value=raw_driver_cost_per_trip)

mpg_inv_times_dpg = Constant(name="(1/(miles per gallon)) x dollars per gallon", 
                                symbol="mpg_inv_times_dpg", 
                                value=(1/raw_mpg)*raw_dollars_per_gallon)


display(dcpt)

# Site adjacency to cities
s_adj = TensorConstant(name="What cities are adjacent to a given site",
                      symbol="s_adj",                      
                      shape=s_adj_raw.shape,
                      values=e_adj_raw_list)
display(s_adj)

city_pops = TensorConstant(name="City populations", 
                           symbol="cpop", 
                           shape=[cities.shape[0],1],
                           values=cities.loc[:,["pop"]].values.tolist()
                           )

display(city_pops)

total_pop = Constant(name="Total population of interest", 
                     symbol="tpop", 
                     value=float(sum(cities.loc[:,"pop"])))

display(total_pop)

TensorConstant(name='Site SVI', symbol='svi', shape=[1, 60], values=['List', ['List', 0.5942, 0.5475, 0.5475, 0.5475, 0.923333333, 0.923333333, 0.4725, 0.9325, 0.923333333, 0.5942, 0.4375, 0.4375, 0.9183, 0.9183, 0.9183, 0.4508, 0.923333333, 0.39, 0.5942, 0.19, 0.3275, 0.4142, 0.3508, 0.3992, 0.5625, 0.565, 0.1958, 0.1, 0.0675, 0.7117, 0.66, 0.3217, 0.0625, 0.1058, 0.4375, 0.6767, 0.5475, 0.16625, 0.9183, 0.1633, 0.7117, 0.923333333, 0.9325, 0.2633, 0.3483, 0.095, 0.2467, 0.0967, 0.5517, 0.195, 0.6392, 0.4725, 0.3467, 0.5625, 0.9183, 0.9183, 0.9183, 0.9183, 0.923333333, 0.923333333]])

TensorConstant(name='Expected attendance', symbol='ea', shape=[1, 60], values=['List', ['List', 3.0, 3.0, 2.0, 3.0, 3.0, 3.0, 6.0, 3.0, 6.0, 4.0, 0.0, 2.0, 3.0, 3.0, 2.0, 7.0, 3.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 7.0, 3.0, 2.0, 4.0, 6.0, 1.0, 3.0]])

TensorConstant(name='Expected under-attendance', symbol='eua', shape=[1, 60], values=['List', ['List', 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1]])

TensorConstant(name='The distance to drive from home to a site', symbol='sd2h', shape=[1, 60], values=['List', ['List', 8.81, 17.85, 17.85, 17.85, 26.28, 26.28, 50.39, 91.69, 26.28, 8.81, 69.13, 69.13, 24.99, 24.99, 24.99, 19.5, 26.28, 0.0, 8.81, 31.26, 102.21, 66.05, 36.16, 70.66, 51.03, 44.79, 35.97, 57.86, 52.05, 48.76, 39.74, 47.6, 60.42, 35.75, 69.13, 38.76, 17.85, 50.5, 24.99, 52.09, 48.76, 26.28, 91.69, 84.84, 71.7, 79.5, 69.38, 78.84, 49.06, 68.87, 53.51, 50.39, 34.99, 51.03, 24.99, 24.99, 24.99, 24.99, 26.28, 26.28]])

Constant(name='Miles per gallon (miles/gallon)', symbol='mpg', value=6.0)

Constant(name='Dollars per gallon ($/gallon)', symbol='dpg', value=3.0)

Constant(name='Driver cost per trip ($)', symbol='dcpt', value=76)

TensorConstant(name='What cities are adjacent to a given site', symbol='s_adj', shape=[36, 60], values=['List', ['List', 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], ['List', 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1], ['List', 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], ['List', 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], ['List', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

TensorConstant(name='City populations', symbol='cpop', shape=[36, 1], values=['List', ['List', 5334], ['List', 837], ['List', 3967], ['List', 517], ['List', 560], ['List', 3565], ['List', 2160], ['List', 1102], ['List', 1791], ['List', 7117], ['List', 774], ['List', 1923], ['List', 1350], ['List', 525], ['List', 969], ['List', 1455], ['List', 7947], ['List', 676], ['List', 2177], ['List', 35579], ['List', 35999], ['List', 3046], ['List', 601], ['List', 706], ['List', 3034], ['List', 946], ['List', 4456], ['List', 966], ['List', 1204], ['List', 1067], ['List', 8397], ['List', 2198], ['List', 793], ['List', 6698], ['List', 9957], ['List', 749]])

Constant(name='Total population of interest', symbol='tpop', value=161142.0)

## Variables

In [9]:
sv = TensorVariable(
  name="Sites visited",                  
  symbol="sv",
  variable_type=VariableTypeEnum.integer,
  shape=[sites.shape[0],1],
  lowerbounds=0,
  upperbounds=1,
  initial_values=0)

display(sv)

cover = TensorVariable(
    name="Coverage of cities",
    symbol="cover", 
    variable_type=VariableTypeEnum.integer,
    shape=[adjTTime.shape[0],1],
    lowerbounds=0,
    upperbounds=1,
    initial_values=0)

cover

TensorVariable(name='Sites visited', symbol='sv', variable_type=<VariableTypeEnum.integer: 'integer'>, shape=[60, 1], lowerbounds=0, upperbounds=1, initial_values=0)

TensorVariable(name='Coverage of cities', symbol='cover', variable_type=<VariableTypeEnum.integer: 'integer'>, shape=[36, 1], lowerbounds=0, upperbounds=1, initial_values=0)

## Constraints

Number of sites is $s$, number of cities is $c$

`sv` = 
$\begin{bmatrix}
x_1\\
x_2\\
⋮ \\
x_s\\
\end{bmatrix}$

- determines whether or not a given site is visited. 
- a binary vector of size $s$ 
- $s$ is the number of sites under consideration


`cover` = 
$\begin{bmatrix}
x^{'}_1\\
x^{'}_2\\
⋮ \\
x^{'}_c\\
\end{bmatrix}$

- A support variable that represents whether a city is covered by the given subset of selected sites in `sv.
- A binary vector of size $c$
- $c$ is the number of cities under consideration

`s_adj` = 
$\begin{bmatrix}
d_{11},…,d_{1s}   \\
⋮,⋱,⋮,\\
d_{c1},…,d_{cs}   \\
\end{bmatrix}$

- A constant that represents whether or not a given site (in the columns) is adjacent to a give city (in the rows)

In [10]:
# sv = [18, 1]
# cover [28, 1]
# s_adj [28, 18]
# [28, 18] . [18, 1] = [28, 1]


g = Constraint(
      name="Desert constraint",
      symbol="c",
      func="cover-s_adj@sv",
      cons_type=ConstraintTypeEnum.LTE,
      is_convex=False,
      is_linear=True,
      is_twice_differentiable=True)

## Objectives

In [11]:

# REMEMBER! If you change the objective, you may need to change the table formatting in step02
# Total patients seen 
total_patients = Objective(
    name = "Maximize total patients served",
    symbol = "f_1", 
    maximize = True,
    is_twice_differentiable=True,
    func = "Sum(ea@sv)"                                    
)

# Underattended sites
under_attended_sites = Objective(
    name = "Minimize the number sites taht are under-attended", 
    symbol = "f_2",
    maximize = False,
    is_twice_differentiable=True,
    func = "Sum(eua@sv)"                                
)

# Cost of events
costs = Objective(
    name = "Minimize total costs ($)",
    symbol = "f_3",
    maximize = False,
    is_twice_differentiable=True,
    func = "Sum(sd2h@sv)*mpg_inv_times_dpg + Sum(sv)*dcpt"    
)

# cpop: [1, 28]
# cover: [28, 1]
coverage = Objective(
    name = "Maximize population with clinic access", 
    symbol = "f_4", 
    maximize = True, 
    is_twice_differentiable=True,
    func = "Sum(cover*cpop)"
)

cumul_svi = Objective(
    name = "Cumulative SVI", 
    symbol = "f_5", 
    maximize = True, 
    is_twice_differentiable=True, 
    func = "Sum(svi@sv)"
)

## Problem

In [12]:
prob = Problem(
        name="Simple site selection",
        description="Simple implementation of the site selection problem",
        is_linear=True,
        is_convex=False,
        is_twice_differentiable=True,
        constraints=[g],
        constants=[eua, ea, sd2h, mpg, dpg, dcpt, s_adj, city_pops, total_pop, mpg_inv_times_dpg, svi],
        variables=[sv, cover],
        objectives=[total_patients, under_attended_sites, costs, coverage, cumul_svi]
    )

## Ideal/nadir

In [14]:

# f_1 Total patients seen 
# f_2 Underattended sites
# f_3 Cost of events
# f_4 Number of citizens covered

# f_1 ideal is seeing all patients, nadir is seeing no patients
all_patients = int(np.sum(sites.loc[:,"medAtt"]))

# f_2 ideal is having no under-attended sites
# f_2 naird is having visiting all locations with under-attended sites
all_ose = int(np.sum(raw_under_attendance))


# How many miles are driven/gas costs
max_dist = sites.loc[:,"dist2home"].sum()
total_gas_cost = (max_dist / raw_mpg) * raw_dollars_per_gallon
driver_cost = sites.shape[0]*raw_driver_cost_per_trip
max_costs = float(driver_cost + total_gas_cost)

# Total number of people
total_citizens = int(cities.loc[:,["pop"]].sum().values[0])

# Maximum SVI score
max_cumul_svi = float(np.sum(raw_svi))

prob = prob.update_ideal_and_nadir(
    new_ideal={
        "f_1": all_patients,
        "f_2": 0, 
        "f_3": 0, 
        "f_4": total_citizens,
        "f_5": max_cumul_svi
        }, 
    new_nadir={
        "f_1": 0,
        "f_2": all_ose,
        "f_3": max_costs, 
        "f_4": 0,
        "f_5": 0
        }
    )


print(f"Ideal values: {prob.get_ideal_point()}")
print(f"Nadir values: {prob.get_nadir_point()}")

Ideal values: {'f_1': 298, 'f_2': 0, 'f_3': 0, 'f_4': 161142, 'f_5': 32.842883330999996}
Nadir values: {'f_1': 0, 'f_2': 17, 'f_3': 5862.45, 'f_4': 0, 'f_5': 0}

## RPM solver

In [16]:
from desdeo.mcdm.reference_point_method import rpm_solve_solutions
from itertools import product
from desdeo.tools import PyomoBonminSolver, PyomoCBCSolver, PyomoGurobiSolver, PyomoIpoptSolver
from desdeo.tools import NevergradGenericSolver

ref_resolution = 3

f_1_ref = np.linspace(prob.get_ideal_point()["f_1"], prob.get_nadir_point()["f_1"],ref_resolution).tolist()
f_2_ref = np.linspace(prob.get_ideal_point()["f_2"], prob.get_nadir_point()["f_2"],ref_resolution).tolist()
f_3_ref = np.linspace(prob.get_ideal_point()["f_3"], prob.get_nadir_point()["f_3"],ref_resolution).tolist()
f_4_ref = np.linspace(prob.get_ideal_point()["f_4"], prob.get_nadir_point()["f_4"],ref_resolution).tolist()
f_5_ref = np.linspace(prob.get_ideal_point()["f_5"], prob.get_nadir_point()["f_5"],ref_resolution).tolist()
#f_1_ref = [200]
#f_2_ref = [10]
#f_3_ref = [1000]
#f_4_ref = [0.5]

pf_samples_raw = []
i = 0 
for ref in product(f_1_ref, f_2_ref, f_3_ref, f_4_ref, f_5_ref):
    reference_point = {"f_1": ref[0], "f_2": ref[1], "f_3": ref[2], "f_4": ref[3], "f_5": ref[4]}

    print(f"Calculating for ref #{i} {reference_point}")
    try: 
        res = rpm_solve_solutions(prob, reference_point=reference_point, solver=PyomoGurobiSolver)
        pf_samples_raw.append(res)
    except ValueError:
        print("Error running for that ref.")
    i += 1

Calculating for ref #0 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #1 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #2 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #3 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #4 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #5 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #6 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #7 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #8 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #9 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #10 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #11 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #12 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #13 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #14 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #15 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #16 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #17 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #18 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #19 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #20 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #21 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #22 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #23 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #24 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #25 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #26 {'f_1': 298.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #27 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #28 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #29 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #30 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #31 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #32 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #33 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #34 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #35 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #36 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #37 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #38 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #39 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #40 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #41 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #42 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #43 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #44 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #45 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #46 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #47 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #48 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #49 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #50 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #51 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #52 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #53 {'f_1': 298.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #54 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #55 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #56 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #57 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #58 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #59 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #60 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #61 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #62 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #63 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #64 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #65 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #66 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #67 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #68 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #69 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #70 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #71 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #72 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #73 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #74 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #75 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #76 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #77 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #78 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #79 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #80 {'f_1': 298.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #81 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #82 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #83 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #84 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #85 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #86 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #87 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #88 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #89 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #90 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #91 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #92 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #93 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #94 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #95 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #96 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #97 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #98 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #99 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #100 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #101 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #102 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #103 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #104 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #105 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #106 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #107 {'f_1': 149.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #108 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #109 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #110 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #111 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #112 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #113 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #114 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #115 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #116 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #117 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #118 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #119 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #120 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #121 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #122 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #123 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #124 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #125 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #126 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #127 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #128 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #129 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #130 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #131 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #132 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #133 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #134 {'f_1': 149.0, 'f_2': 8.5, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #135 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #136 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #137 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #138 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #139 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #140 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #141 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #142 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #143 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #144 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #145 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #146 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #147 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #148 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #149 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #150 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #151 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #152 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #153 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #154 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #155 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #156 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #157 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #158 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #159 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #160 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #161 {'f_1': 149.0, 'f_2': 17.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #162 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #163 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #164 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #165 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #166 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #167 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #168 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #169 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #170 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 0.0, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #171 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #172 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #173 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #174 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #175 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #176 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #177 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #178 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #179 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 2931.225, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #180 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #181 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #182 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #183 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 32.842883330999996}
Calculating for ref #184 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 16.421441665499998}
Calculating for ref #185 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 80571.0, 'f_5': 0.0}
Calculating for ref #186 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 32.842883330999996}
Calculating for ref #187 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 16.421441665499998}
Calculating for ref #188 {'f_1': 0.0, 'f_2': 0.0, 'f_3': 5862.45, 'f_4': 0.0, 'f_5': 0.0}
Calculating for ref #189 {'f_1': 0.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 32.842883330999996}
Calculating for ref #190 {'f_1': 0.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 16.421441665499998}
Calculating for ref #191 {'f_1': 0.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 161142.0, 'f_5': 0.0}
Calculating for ref #192 {'f_1': 0.0, 'f_2': 8.5, 'f_3': 0.0, 'f_4': 80571.0, 'f_5': 32.842883330999996}

## Send relevant data to a pkl file

In [1]:
import pickle
output = open(f'data/pf_test.pkl', 'wb')
pickle.dump({"pf": pf_samples_raw,
             "prob" : prob,
             "cities": cities,
             "sites": sites,
             "cities_adj2sites": cities_adj2sites, 
             "total_pop": total_citizens
             }, output)

NameError: name 'pf_samples_raw' is not defined